id: A11224349
title: Supplication to Lord Mila Shepa Dorje
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:47:05.364454
  last_modified_at: 2022-03-01 00:47:05.364471
