id: A11224349
title: Guru Yoga of Jetsün Shepa Dorje
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:47:05.360386
  last_modified_at: 2022-03-01 00:47:05.360391
