id: A11224349
title: Guru Yoga of Milarepa Shepa Dorje for Daily Practice
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:47:05.362001
  last_modified_at: 2022-03-01 00:47:05.362004
